version: '2'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "drupal"
    networks:
      - default
    volumes:
      - /var/lib/mysql
  app:
    image: kamihicouki/drupal:7-fpm
    expose:
      - "9000"
    networks:
      - default
    volumes:
      - /var/www/html
  web:
    image: nginx:latest
    ports:
      - "80"
      - "443"
    networks:
      - default
    volumes_from:
      - app
    volumes:
      - "./nginx__drupal7.conf:/etc/nginx/conf.d/default.conf"
